# Stage 1: Build the react app
FROM node:20

# Define build arguments for environment variables
ARG VITE_API_URL


# Set environment variables during the build process
ENV VITE_API_BASE_URL=$VITE_API_URL


WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]